version: '3.8'
services:
  blog.postgres:
    image: postgres:12.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
